from enum import Enum


class SfType(Enum):
    ACCESS = "SF_Access"
    ASTRO_TIMER_LOGIC_PROGRAM = "SF_AstroTimerLogicProgram"
    AUDIO = "SF_Audio"
    AUTOMATION = "SF_Automation"
    CALENDAR_TIMER_LOGIC_PROGRAM = "SF_CalendarTimerLogicProgram"
    CLIMA = "SF_Clima"
    DATE_TIME_CONFIG = "SF_DateTimeConfig"
    DATE_TIME_SETTING = "SF_DateTimeSetting"
    ENERGY = "SF_Energy"
    IRRIGATION = "SF_Irrigation"
    IRRIGATION_LOGIC_PROGRAM = "SF_IrrigationLogicProgram"
    LIGHT = "SF_Light"
    LOGIC_PROGRAM = "SF_LogicProgram"
    SCENE = "SF_Scene"
    SCENE_ACTIVATOR = "SF_SceneActivator"
    SENSOR = "SF_Sensor"
    SERVICE = "SF_Service"
    SHUTTER = "SF_Shutter"
    TELEMETRY_ENERGY = "SF_TelemetryEnergy"
    TELEMETRY_GAS = "SF_TelemetryGas"
    TELEMETRY_WATER = "SF_TelemetryWater"
